### ISSUE TITLE
Misconfiguration on Android stock browser

### ISSUE THREAD

**Issue by ArchGalileu** [hibbitts-design/grav-skeleton-eportfolio-blog#1]
The blog page stays very messy on Chromium for Android on Lineage Os

http://tinypic.com/r/10pxf9v/9

Best regards 
ArchGalileu

**Comment by paulhibbitts** [comment]
Hi @ArchGalileu,

This skeleton uses the stock Gantry 5 theme `Helium` with some additional items for Git Sync config and sidebar display. Does `Helium` itself also have this issue? Here is the list of supported Browsers for Gantry: http://docs.gantry.org/gantry5/basics/system-requirements#browser-requirements

Hope the above helps,
Paul
