### ISSUE TITLE
howto use the sidebar content?

### ISSUE THREAD

**Issue by ArchGalileu** [hibbitts-design/grav-skeleton-eportfolio-blog#2]
Can't realise how to use it :(

Best regards
ArchGalileu

**Comment by paulhibbitts** [comment]
Hello ArchGalileu,

To enable the display of the sidebar from the Grav Admin Panel do the following:

1. Tap `Gantry 5`
2. Tap `Layout` tab
3. Scroll down until you see the `container` area and tap in the config icon (gears) for the `Custom HTML` particle within the `Sidebar` area
4. Enable the particle by tapping on the upper-right toggle
5. Tap `Apply and Save`

The sidebar should now be displayed. You can change the content of your sidebar by editing the markdown file in the `sidebar` folder.

In a future release I will explore if I can make this more apparent, for example perhaps with the automatic display of the sidebar if the sidebar markdown file is not empty.

Hope the above is of help.
Paul
