### ISSUE TITLE
Run in root directory?

### ISSUE THREAD

**Issue by kescobo** [hibbitts-design/grav-skeleton-eportfolio-blog#3]
I'd like to use grav in the root directory of my website rather than a subdirectory (eg http://nequals.me rather than http://nequals.me/blog/). It works fine when I extract into a sub directory (`public_html/blog/`, but when I try to move the files to the root (`public_html`), I get an error when I navigate to the website.

```
Not Found

The requested URL /admin was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

Using reclaim hosting if it makes a difference.

**Comment by kescobo** [comment]
Nevermind - the issue is that I wasn't moving the hidden (dot) files over from the subfolder to to root. I think it's working now.

**Comment by paulhibbitts** [comment]
Glad you got it sorted!
