### ISSUE TITLE
Unattributed commits

### ISSUE THREAD

**Issue by flaviocopes** [hibbitts-design/grav-skeleton-eportfolio-blog#4]
Hi Paul, just stumbled on the commits list and I see they are not all attributed to your GitHub user -
 https://github.com/hibbitts-design/grav-skeleton-eportfolio-blog/commits/master

Not a big deal but it's easily fixable by adding the email used in those commits to your GitHub account https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

👍

**Comment by paulhibbitts** [comment]
Thanks for the heads-up @flaviocopes 🙂 Indeed, I did not have my hibbittsdesign.org email associated with my GitHub account. I've updated this now and my commits are now attributed properly👍.

Thanks again,
Cheers
