### ISSUE TITLE
How to show archive plugin content in sidebar

### ISSUE THREAD

**Issue by edwigemorin** [hibbitts-design/grav-skeleton-eportfolio-blog#5]
Hello,
Thank you for your great skeleton. 

I've already tested other skeleton without Gantry with no problem but now with the skeleton-eportfolio-blog I cannot figure out how to show the archive plugin list in the sidebar.

Could you help please.
Thank you in advance.
Best regards

**Comment by paulhibbitts** [comment]
Hi @edwigemorin, glad you are finding the skeleton useful.

Some of Grav's standard plugins that display information will not work right away with Gantry (such as Archives). In the ePortfiolio Blog I've created several Particles such as Blog Search and Blog Tags to work around this issue, so in theory the same approach could be used to create an Archives Particle - does that help?

**Comment by paulhibbitts** [comment]
Ok, so I took a quick look into this and it is pretty straightforward to add an Archives Particle using the existing Plugin.

Expand the attached ZIP file, and place both resulting files into the folder:
`/user/themes/g5_helium/custom/particles`

I would also turn off the Gantry Cache (i.e. set "Extras" to "Development") and clear cache. You should then see a new Particle called "Blog Archives" that you could drag and drop into your page layout.

Please let me know if this works for you.

[Archives Particle.zip](https://github.com/hibbitts-design/grav-skeleton-eportfolio-blog/files/1180719/Archives.Particle.zip)

**Comment by edwigemorin** [comment]
Hi @paulhibbitts and thank you very much.
It's just great, I've done exactly as you mentioned and it worked out of the box :-)

The particle "Blog Archives" appear and I place it in the page layout, flush the cache and that it ! The archives list appear in the sidebar.

Thank you for your quick answer and solution.

**Comment by paulhibbitts** [comment]
Awesome @edwigemorin, great to hear!

BTW, I just learned of an issue with future Grav/Gantry upgrades: you should move all the folders within the `user/themes/g5_helium/custom/` folder to `user/data/gantry5/themes/g5_helium/`.

For example, here is my version of that folder:
![2017-07-27_12-38-00](https://user-images.githubusercontent.com/1812771/28688903-73120b96-72c8-11e7-94d8-33e9fbc74cc5.png)

I will be releasing an updated ePortfolio Blog soon with this change, and also including the new Archives Particle.

Please let me know if the above works for you.

Thanks,
Paul

**Comment by edwigemorin** [comment]
Yes it worked. I moved "particles", "scss" and "templates" one level up and delete the empty folder "custom". I'm not surprise with this change because other skeletons that I've tested did not had this custom folder.

During the move I had to merge the files with already existing folder for "particles" and "scss" but every thing was OK.
Thank You :-)
Edwige

**Comment by paulhibbitts** [comment]
Please be sure to move everything into the 'data' folder - by the sounds of it you moved everything up a level vs. into a completely different location 🙂

I will now close this issue, but please feel free to re-open if needed.
